version: '3.9'
services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: pos
      POSTGRES_USER: posuser
      POSTGRES_PASSWORD: pospass
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
  redis:
    image: redis:7-alpine
    ports:
      - '6379:6379'

volumes:
  pgdata:
